# Generated by Django 4.2.7 on 2023-12-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_openid'),
        ('users', '0005_myuser_nickname_alter_myuser_openid'),
    ]

    operations = [
    ]
