# Generated by Django 4.2.7 on 2023-11-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_entry_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
    ]
