# Generated by Django 4.2.7 on 2023-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='expense', max_length=10),
        ),
    ]
