# Generated by Django 4.2.7 on 2023-11-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_category_alter_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
