# Generated by Django 4.2.7 on 2023-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_category_category_type_category_icon_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
