# Generated by Django 4.2.7 on 2023-11-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0009_alter_ledger_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quarter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('week', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ledger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.ledger')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
