# Generated by Django 4.2.7 on 2023-11-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='month_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledger',
            name='year_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
