# Generated by Django 4.2.7 on 2023-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_ledgermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[('personal', '个人账本'), ('family', '家庭账本'), ('group', '群组账本')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='ledgermember',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ledgermember',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgermember',
            name='role',
            field=models.CharField(choices=[('bot', '机器人'), ('owner', '账本主人'), ('admin', '管理员'), ('member', '普通成员')], default='member', max_length=10),
        ),
    ]
