# Generated by Django 4.2.7 on 2023-12-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_ledger_ledger_type_ledgermember_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='user',
        ),
    ]
