# Generated by Django 4.2.7 on 2023-12-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_ledgermember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgermember',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
