# Generated by Django 4.2.7 on 2023-12-21 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_ledgermember_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.ledger'),
        ),
    ]
