# Generated by Django 4.2.7 on 2023-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_remove_category_user_category_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='review_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', '未审核'), ('reviewed', '已审核')], default='unreviewed', max_length=10),
        ),
    ]
