# Generated by Django 4.2.7 on 2023-12-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_entry_review_notes_entry_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', '未审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='unreviewed', max_length=10),
        ),
    ]
